# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems: [jekyll-paginate]

# Setup
title:               DigitalReplica
tagline:             'The impact of security, privacy and technology on our daily lives'
description:         'The impact of security, privacy and technology on our daily lives'
url:                 http://www.digitalreplica.org
paginate:            5
permalink:          /:year/:month/:title/
excerpt_separator:  <!--more-->  # you can specify your own separator, of course.

# Conversion
markdown:    kramdown
highlighter: rouge

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# About/contact
author:
  name:              Danny Rappleyea
  url:               http://www.digitalreplica.org
  email:             email

# Custom vars
version:             1.0.0

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      comments: true
